### ISSUE TITLE
Cuphead Cheat broken/Bug

### ISSUE THREAD

**Issue by sotojo01** [WerWolv/EdiZon_CheatsConfigsAndScripts#101]
Cuphead atmosphere cheat.txt file is no good.  It actually causes the game to crash. game will load to the film strip black and white loading screen before the studio MDHR red logo screen then crash claiming the "game cannot start due to an error". Game works perfectly fine once you remove the cheat.txt file from the atmosphere/titles folder.  Other Edizon atmosphere cheats work on other supported games so I isolated it to that file.  

Running ams 0.8.8 ofw 7.0.1

**Comment by zkitX** [comment]
Are you on the latest cuphead version? It works perfectly for me.

**Comment by sotojo01** [comment]
Yes the game won’t start unless you have the update. I’m on title update 1.2.2. I’m also using atmoSphere 0.8.8 on ofw 7.0.1. 

I placed the “title id” folder with the txt cheat file in my atmoSphere titles folder all other games are fine. But cuphead causes my game to crash. I remove that txt file and it loads. It’s really bizarre. I am using the latest edizon. 

Any recommendations?

**Comment by sotojo01** [comment]
https://gbatemp.net/threads/the-software-was-closed-because-an-error-occurred.533703/ This guy is experiencing the same thing as me but with crash bandicot instead.  And if you read the second to last comment he came to a similar conclusion that the presents of the cheat file caused it.  werid its working for you.  I used a NSP via goldleaf v.5  I'm just stumped and would love cheats to work for this game.
