### ISSUE TITLE
Last few codes are missing for Pokémon Let's Go Pikachu

### ISSUE THREAD

**Issue by jhicken** [WerWolv/EdiZon_CheatsConfigsAndScripts#114]
If you look at the list of cheats and compare them to the text file... You will notice that the last few codes from the text file do not show up in the GUI.

Let me know if you would like a screenshot.

**Comment by WerWolv** [comment]
They are extremely long. It's very likely that dmnt:cht stops loading them because it's running out of memory. Nothing I can do about really

**Comment by jhicken** [comment]
There is really nothing that can be done? Sorry I am asking very naive questions because i dont know much about the code base. I just noticed tbe problem.

Like is this an Atmosphere problem?

Is there anything that can be done with like caching the list of inactive codes on the SD card so you can at least see them and when you select them put them in the dmnt:cht?

I saw your PR over here. Im guessing this is all related as well.
https://github.com/Atmosphere-NX/Atmosphere/pull/561

**Comment by WerWolv** [comment]
Yep it is. It would require changing the logic of dmnt:cht fundamentally which is not going to happen. Only thing you can do is try to remove all the cheats you don't care about. Maybe more get loaded then
