### ISSUE TITLE
Hbg shop and edizon

### ISSUE THREAD

**Issue by r2daizzzo** [WerWolv/EdiZon_CheatsConfigsAndScripts#125]
I recently updated my game thur hbg shop now my build I'd has change and I cant use cheat how can I make or find new cheats. Also is there any way I can go to a lower update

**Comment by r2daizzzo** [comment]
Game ver. That is

**Comment by r2daizzzo** [comment]
I'm also interested in making cheat but I'm a noob so is there any way I can learn

**Comment by WerWolv** [comment]
a) Try buying your games...
b) https://gbatemp.net/threads/noexs-hacking-guide.543733/
