### ISSUE TITLE
JoyCons don't work in latest nightly

### ISSUE THREAD

**Issue by GuyInDogSuit** [WerWolv/EdiZon_CheatsConfigsAndScripts#128]
I've launched it both in applet and in full-memory mode (whatever you call it, when you launch HBL the other way by holding R on a game). My controllers are all up to date. Atmosphere is the latest. Not sure what could be the issue.

**Comment by WerWolv** [comment]
Wrong repository and reinstall Atmosphere again. If you're using tinfoil/hbg, delete it and don't install it again after reinstalling Atmosphere

**Comment by GuyInDogSuit** [comment]
Quick question: wrong repository for what? The Edizon nightly, or Atmosphére?

I've been using Goldleaf for its USB installer. Isn't Tinfoil deprecated anyway?

**Comment by WerWolv** [comment]
If you're not using tinfoil (the one with the heart icon) don't bother. Just reinstall Atmosphere by deleting the atmosphere folder and reinstalling it.

It's usually either tinfoil or a outdated sysmodule that's the reason

**Comment by GuyInDogSuit** [comment]
It could be Atmosphére, or it could be RetroReloaded interfering with it. Are you familiar with RR? I use it to manage payloads and plugins (like LAN play), and switch between CFWs (occasionally use SX OS for their apps, but it's been very unstable since 2.9.2). Since I've switched to Atmosphére, I'm thinking of deleting everything but the Nintendo folder and starting fresh again and seeing if things work as they should. Could be some leftover garbage from SX. Could be Retro. Dunno yet.

**Comment by WerWolv** [comment]
Haven't heard of RetroReloaded, sorry. But yeah, reinstalling current Atmosphere is a good idea

**Comment by GuyInDogSuit** [comment]
Alright, will do. I'll report back.
