### ISSUE TITLE
Possible incompatibility with 9.1.0

### ISSUE THREAD

**Issue by TechGeekGamer** [WerWolv/EdiZon_CheatsConfigsAndScripts#131]
Since Atmosphere is renaming the “titles” to ”contents”. Wouldn’t that affect EdiZon?

**Comment by vanpome** [comment]
I tried out the new atmosphere and 9.1.0 firmware, EdiZon is no longer work. Do you have any alternatives to this?

**Comment by Conan179** [comment]
Cheats yes.
Sav edit, sometimes on windows pcs.

**Comment by vanpome** [comment]
@Conan179 does cheats work on 9.1.0 ? Mine doesn't

**Comment by Conan179** [comment]
Of course cheats do not go to 9.1.0 yet. The cfws are not 24h old. You have to wait until the apps have been adjusted.

**Comment by deejay87** [comment]
Edizon is working on 9.1.0
You can use the compatibility for the joy-cons with this setup :
- copy the file :
`atmosphere/config_templates/system_settings.ini`
- to the folder
`atmosphere/config`
- Edit the file and uncomment this line (remove **;**)
`enable_deprecated_hid_mitm = u8!0x0`
- Modifiy the line in the end like this
`enable_deprecated_hid_mitm = u8!0x1`

**Comment by WerWolv** [comment]
Instead, you should all be using the latest EdiZon snapshot you can get on my GitHub page
