### ISSUE TITLE
Not all Cheat TXT file names are lowercase / uppercase as per every other one

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [WerWolv/EdiZon_CheatsConfigsAndScripts#70]

**Comment by WerWolv** [comment]
Question is, should all be uppercase or lowercase? Are there any standards for that?

**Comment by ThatNerdyPikachu** [comment]
No clue — I see both, paging @zkitX

**Comment by zkitX** [comment]
there are no standards, but either work just as intended, but I'll put them all to a certain case if needed.

**Comment by WerWolv** [comment]
I'd make them all lowercase if there is no standard. Looks better imo ^^

**Comment by zkitX** [comment]
zkitx@3d7f514c402e6ee05c48d6e957c5ed8dfa63e957

**Comment by ThatNerdyPikachu** [comment]
@zkitX can you merge this to master?

**Comment by WerWolv** [comment]
Has been merged already @ThatNerdyPikachu
