### ISSUE TITLE
not an issue, just wondering how to use the cheats?

### ISSUE THREAD

**Issue by sudh2020** [WerWolv/EdiZon_CheatsConfigsAndScripts#71]
I put the cheats folder in sd/EdiZon/editor. can you tell me what i'm doing wrong?

**Comment by WerWolv** [comment]
They go into `/atmosphere/titles/<titleID>/cheats`. If you don't want the hassle of moving them there manually, open EdiZon and press the minus button in the main menu to download all the latest files :)
