### ISSUE TITLE
Cheats don't load for Pokémon Let's Go Pikachu

### ISSUE THREAD

**Issue by hibbl** [WerWolv/EdiZon_CheatsConfigsAndScripts#74]
Got all of the txt files in their designated folder. 
Tested the codes of Breath of the Wild and it worked like a charm. 
However, as I start Pokémon Let's Go Pikachu there is no cheat loaded in Edizon.
![NVIDIA_Share_A7eexlHQxv](https://user-images.githubusercontent.com/48002688/54075206-f38dd200-429c-11e9-82ee-c31f9d00293a.jpg)

**Comment by WerWolv** [comment]
The cheats are most likey for version 1.0.0 however the latest version is 1.0.1
