### ISSUE TITLE
Tales of vesperia

### ISSUE THREAD

**Issue by Sounnga** [WerWolv/EdiZon_CheatsConfigsAndScripts#89]
Tales of vesperia cheats in the database are outdated, I found a more updated file here: https://github.com/Ruimusume/TOVR that seem to sort of work with EdiZon even though they are for SXOS. I got some cheats to show up, but not all, and the ones that did show up I couldn't test because of where I was in the game. 
[9e812d3826d6e7ac.txt](https://github.com/WerWolv/EdiZon_CheatsConfigsAndScripts/files/3044045/9e812d3826d6e7ac.txt)
[f244b656b1cafe52.txt](https://github.com/WerWolv/EdiZon_CheatsConfigsAndScripts/files/3044046/f244b656b1cafe52.txt)
Attached are the files I used, they have google translate descriptions but they should be good enough to figure out what each code is.

**Comment by WerWolv** [comment]
Could you give me the titleid of that game as well?

**Comment by Sounnga** [comment]
01002C0008E52000
